server {
    listen 80;
    listen [::]:80;
    server_name opentrad.xyz;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        return 308 https://opentrad.xyz$request_uri;
    }
}
