Foreground yes
TCPSocket 3310
TCPAddr 0.0.0.0
LocalSocket /tmp/clamd.sock
MaxFileSize 55M
MaxScanSize 55M
StreamMaxLength 55M
MaxRecursion 16
MaxFiles 10000
ReadTimeout 120
CommandReadTimeout 15
SendBufTimeout 120
LogTime yes
LogVerbose no
LogClean no
